name: testyfy
description: "Una App para explorar recomendaciones"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_secure_storage: ^9.2.4
  flutter_localizations:
    sdk: flutter
  intl: any
  # dart sdk issue #60784 workaround
  analyzer: 7.3.0
  analyzer_plugin: 0.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint:
  riverpod_lint: ^2.6.4
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5

flutter:
  generate: true
  uses-material-design: true
